
services:
  sirgibblets-site:
    build: .
    container_name: sirgibblets-site
    ports:
      - "8080:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.project=sirgibblets-site"
      - "description=Sir Gibblets"